# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_last_ip_management_ip_and_status_applied'),
        ('config', '0012_auto_20181104_0614'),
    ]

    operations = [
    ]
