# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_last_ip_management_ip_and_status_applied'),
        ('config', '0014_add_relevant_permissions_to_admin_and_operators'),
    ]

    operations = [
    ]
