language: python
sudo: false
cache: pip

addons:
  apt:
    packages:
      - sqlite3
      - gdal-bin
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev

python:
  - "3.4"
  - "2.7"

env:
  - DJANGO="django>=1.11,<1.12"
  - DJANGO="django>=2.0,<2.1"

matrix:
  exclude:
   - python: "2.7"
     env: DJANGO="django>=2.0,<2.1"

branches:
  only:
    - master

before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt
  - ./runflake8
  - ./runisort

install:
  - pip install $DJANGO
  # fix issues with travis
  - pip install "attrs>=17.4.0"
  - pip install "six>=1.11.0"
  - python setup.py -q develop
  # TODO: temporary, remove when django-netjsonconfig 0.9.0 is released
  - pip install https://github.com/openwisp/django-netjsonconfig/tarball/master
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then pip install git+git://github.com/tinio/pysqlite.git@extension-enabled#egg=pysqlite; fi
  - pip install git+https://github.com/openwisp/openwisp-users.git
  # TODO: temporary, remove when django-x509 is released with the passphrase add-on
  - pip install https://github.com/openwisp/django-x509/tarball/master

script:
  # for some reason the migrations check is failing only on django 2.0
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then ./tests/manage.py makemigrations config pki --dry-run | grep "No changes detected"; fi
  - coverage run --source=openwisp_controller runtests.py

after_success:
  coveralls
